config/routes.rb
Rails.application.routes.draw do
  get 'signin', to: 'sessions#new'
  post '/sessions/create', to: 'session#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'car_count', to: 'cars#car_count'
  get 'ajax_booking', to: 'bookings#ajax_booking'
  get 'ajax_edit_booking', to: 'bookings#ajax_edit_booking'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :users do
   resources :bookings
  end

  resources :cars, only: [:index, :show]

  namespace :admin do
    resources :bookings, :only => [:index, :show]
    resources :cars, only: [:new, :create, :edit, :update, :destroy, :show, :index]
    resources :home, only: [:index]
  end

  root 'static_pages#home'

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car


  def valid_date
    self.start_date < self.end_date
  end

  def duplicate_booking
    Booking.all.each do |booking|
      if booking.id != self.id
        if booking.car == self.car
          if self.start_date <= booking.end_date && self.start_date >= booking.start_date || self.end_date <= booking.end_date && self.end_date >= booking.start_date
            return true
          end
        end
      end
    end
  end

  def return_available_dates
    Booking.all.each do |booking|
      if self.start_date <= booking.end_date && self.start_date >= booking.start_date || self.end_date <= booking.end_date && self.end_date >= booking.start_date
          return "This car is not available between #{booking.start_date} and #{booking.end_date}. Choose another time! Thanks."
      end
    end
  end

  def revenue
    "$" + (( self.end_date - self.start_date ).to_i * self.car.price_per_day).to_s
  end





end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @cars = Car.all
  end

  def show
    @booking = Booking.find_by_id(params[:id])
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def ajax_booking
      @user = User.find_by_id(params[:user_id])
      @car = Car.find_by_id(params[:car_id])
      @booking = Booking.new
      render partial: "ajaxnew", locals: {user: @user, car: @car}
  end

  def ajax_edit_booking
      @user = User.find_by_id(params[:user_id])
      @booking = Booking.find_by_id(params[:id])
      render partial: "ajaxedit", locals: {booking: @booking}
  end

  def index
    @bookings = Booking.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @bookings}
    end
  end

  def show
    @booking = Booking.find_by_id(params[:id])
    @user = @booking.user
  end

  def new
    @user = User.find_by_id(params[:user_id])
    @car = Car.find_by_id(params[:car_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @car = @booking.car
    if @booking.valid? && @booking.valid_date && @booking.duplicate_booking != true
      @booking.save
      respond_to do |f|
        f.html {redirect_to user_path(@booking.user)}
        f.json {render :json => @booking.user}
      end
    else
      if !@booking.valid_date
        flash[:message] = "Check your dates and try again!"
      elsif @booking.duplicate_booking
        flash[:message] = @booking.return_available_dates
      end
      respond_to do |f|
        f.html {redirect_to user_path(@booking.user)}
        f.json {render :json => @booking.user }
      end
    end
  end

  def edit
    @booking = Booking.find_by_id(params[:id])
    @user = @booking.user
  end

  def update
    @booking = Booking.find_by_id(params[:id])
    @booking.assign_attributes(booking_params)
    if @booking.valid_date && @booking.duplicate_booking != true
        @booking.save(booking_params)
        respond_to do |f|
          f.html {redirect_to user_path(@booking.user)}
          f.json {render :json => @booking.user}
        end
    else
      if !@booking.valid_date
        flash[:message] = "Check your dates and try again!"
      elsif @booking.duplicate_booking
        flash[:message] = @booking.return_available_dates
      end
      respond_to do |f|
        f.html {redirect_to user_path(@booking.user)}
        f.json {render :json => @booking.user}
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to @user
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :car_id, :user_id)
  end

end

app/views/admin/bookings/index.html.erb
<h1>Current Bookings</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="7"></th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <th align = "left">Name  </th> <!-- this will be where the sort-links will be-->
      <th align = "center">Admin Privileges </th>
      <th>Start Date  </th>
      <th>End Date  </th>
      <th>Car </th>
      <th>Total Booking Revenue </th>
    </tr>

    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.name %>
        <td align = "center"><%= booking.user.admin.to_s.titleize %>
        <td><%= booking.start_date %>
        <td><%= booking.end_date %>
        <td><%= booking.car.name %>
        <td  align = "center" ><%= booking.revenue %>
        <td><%= link_to "Details", admin_booking_path(booking) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/bookings/show.html.erb
<h2> Booking Details </h2>

<p> User: <%= @booking.user.name %>
<p> Start Date: <%= @booking.start_date %>
<p> End Date: <%= @booking.end_date %>
<p> Created At: <%= @booking.created_at %>
<p> Updated At (if applicable): <%= @booking.updated_at %>

<p> Total Booking Revenue: <%= @booking.revenue %></p>