config/routes.rb
Rails.application.routes.draw do
  get 'signin', to: 'sessions#new'
  post '/sessions/create', to: 'session#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'car_count', to: 'cars#car_count'
  get 'ajax_booking', to: 'bookings#ajax_booking'
  get 'ajax_edit_booking', to: 'bookings#ajax_edit_booking'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :users do
   resources :bookings
  end

  resources :cars, only: [:index, :show]

  namespace :admin do
    resources :bookings, :only => [:index, :show]
    resources :cars, only: [:new, :create, :edit, :update, :destroy, :show, :index]
    resources :home, only: [:index]
  end

  root 'static_pages#home'

end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  has_many :users, through: :bookings

  validates :name, presence: true
  validates :top_speed, numericality: true
  validates :range, numericality: true
  validates :charge_time, numericality: true
  validates :price_per_day, numericality: true

  scope :fastestcar, -> {order('top_speed DESC').first.name}



end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find_by_id(params[:id])

  end


  def new
    @car = Car.new
  end

  def update
      if @car.update(car_params)
        redirect_to admin_cars_path, notice: "Car details were successfully updated."
      else
        render :edit
      end
  end

  def create
    @car = Car.new(car_params)
    if @car.valid?
        @car.save
        redirect_to admin_cars_path, notice: "Car was successfully added."
    else
      render :new
    end

  end

  def destroy
    @car.destroy
    redirect_to admin_cars_path, notice: "Car was successfully deleted."
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(
      :name,
      :top_speed,
      :range,
      :charge_time,
      :price_per_day
    )
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def car_count
    render json: Car.count
  end

  def index
    @cars = Car.order("#{sort_column} #{sort_direction}")
    @user = User.find_by_id(params[:user_id])
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @cars.to_json }
    end
  end

  def show
    @car = Car.find_by_id(params[:id])
    @user = User.find_by_id(params[:user_id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @car.to_json }
    end
  end

  def new
    @car = Car.new
  end

  def update
      if @car.update(car_params)
        redirect_to @car, notice: "Car details were successfully updated."
      else
        render :edit
      end
  end

  def create
    @car = Car.new(car_params)

    if @car.valid?
        @car.save
        redirect_to car_path(@car.id)
    else
      render :new
    end

  end

  def destroy
    @car.destroy
    redirect_to cars_url, notice: "Car was successfully deleted."
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(
      :name,
      :top_speed,
      :range,
      :charge_time,
      :price_per_day
    )
  end

  def sortable_columns
    ["name", "top_speed", "range", "charge_time", "price_per_day"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/cars_helper.rb
module CarsHelper

 def sort_link(column, title = nil)
   title ||= column.titleize
   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
   icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
   icon = column == sort_column ? icon : ""
   link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
 end

end

app/views/admin/cars/_form.html.erb
<br>
<%= form_for @car, :url => {:controller => "admin/cars", :action => "create"} do |f| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:
      </h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "Name" %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :top_speed, "Top Speed in km/h"%><br>
  <%= f.text_field :top_speed %><br><br>

  <%= f.label :range, "Range per Charge in km"%><br>
  <%= f.text_field :range %><br><br>

  <%= f.label :charge_time, "Charge up time in hours"%><br>
  <%= f.text_field :charge_time %><br><br>

  <%= f.label :price_per_day, "Rental Price per Day"%><br>
  <%= f.text_field :price_per_day %><br><br>

  <%= f.submit %>


<% end %>

app/views/admin/cars/edit.html.erb
<h1>Editing car</h1>

<br>
<%= form_for @car, :url => {:controller => "admin/cars", :action => "update"} do |f| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:
      </h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "Name" %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :top_speed, "Top Speed in km/h"%><br>
  <%= f.text_field :top_speed %><br><br>

  <%= f.label :range, "Range per Charge in km"%><br>
  <%= f.text_field :range %><br><br>

  <%= f.label :charge_time, "Charge up time in hours"%><br>
  <%= f.text_field :charge_time %><br><br>

  <%= f.label :price_per_day, "Rental Price per Day"%><br>
  <%= f.text_field :price_per_day %><br><br>

  <%= f.submit %>


<% end %>

<br>
<br>

<%= link_to 'Delete this car', admin_car_path(@car),
          data: {:confirm => 'Are you sure?'}, :method => :delete %>

app/views/admin/cars/index.html.erb
<h1>Car List</h1>

<%= flash[:notice] %>
<br>
<br>


<table class="table">
  <thead>
    <tr>
      <th colspan="7"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th align = "left">Name</th> <!-- this will be where the sort-links will be-->
      <th></th>
    </tr>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %>
        <td><%=link_to "Edit", edit_admin_car_path(car) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to "Add a new car", new_admin_car_path%>

app/views/admin/cars/new.html.erb
<%= render 'form' %>

app/views/admin/cars/show.html.erb
<p> You've successfully added the <%= @car.name %>. Confirming details below:</p>

<ul>
    <li><p>Top Speed: <%= @car.top_speed %> km/hr </p></li>
    <li><p>Range: <%= @car.range %> km </p></li>
    <li><p>Charge Time: <%= @car.charge_time %> hrs </p></li>
    <li><p>Price (per Day): $<%= @car.price_per_day %> </p></li>
</ul>

<%= link_to "Back to Car List", admin_cars_path %>